name: shield
description: "S.H.I.E.L.D. project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^15.0.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
          weight: 400

flutter_native_splash:
  color: '#171717'
  image: assets/images/logo.jpg
  android: true
  ios: true
  web: false
